name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Download and set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 19  # 适用于 Android 4.0
        build-tools: '30.0.2'

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyApp
        path: app/build/outputs/apk/debug/app-debug.apk
